### ISSUE TITLE
Bootstrapping Issue

### ISSUE THREAD

**Issue by alexeagle** [bazel-contrib/bazelrc-preset.bzl#1]
Hey @hofbi and @fmeum - you've both been active in bazel-lib on this feature set, so I'm hoping we can do some design over here and get this repo bootstrapped and published.

**Comment by hofbi** [comment]
this is what we've got so far

## still publish/deliver as a ruleset?

* to me this still makes sense
* if not, what would be the alternative?

## still use write_source_files to vendor presets into user repo?

* to me this is still a good way to use it as the user can control when to update the flags and what presets changed
* we could think about restructuring the bazelrc files though.
    * For instance, when I was adding flags such as https://github.com/bazel-contrib/bazel-lib/pull/1108, I added them to bazelX rc files where needed. But they might also fit to convenience or so.
    * The other way round, https://github.com/bazel-contrib/bazel-lib/pull/1017 moved flags from performance.bazelrc to the bazel versioned files because the default value changed.
    * Ideally, we would only have to maintain a single list of flags and default values we care about and generate the presets from this input depending on the bazel version used and if the flag is available for this version at all.

## use bazel help --flags-as-proto as a datasource to be more comprehensive?

* if we are generating the final presets, this could help use to be notified if default values changed in new versions, etc.

**Comment by hofbi** [comment]
Thinking about the goals of these presets might also help with how we design this. Ideally bazel's default values should be a good starting point. These presets can provide 

- common flags/settings that for some reason are not (yet) the default value in bazel
- provide a way to backport useful default values to older bazel versions such as with bazel-lib#1108
- provide special presets such as for debugging and CI 

Anything else?

----

Second topic again related to generating the final preset file. This would allow us to maintain a consistent structure in the presets. We could always include a link to the documentation, a reason for the present, etc.

**Comment by fmeum** [comment]
+1 to generating a single preset given the relevant inputs (Bazel version, perhaps level of "opinionatedness"). We should probably start with recommended incompatible flags as well as backports of defaults from higher Bazel versions, as well as the debug/CI/... configs. When that's done, we can venture into more opinionated settings.

**Comment by hofbi** [comment]
Would you generate a single preset file with all recommended flags? How would we handle things like CI and debug? As of now they are probably added e.g. in CI with `--bazelrc=ci.bazelrc`. Would we place them into a config then to be used with `--config=ci`?

If we would follow the preset generation approach, I can see this workflow:

* Presets input datastructure
* Generation unit (find default value of bazel version we want to backport from, generate documentation links based on users bazel version, etc.)
* Output preset bazelrc file
* write_source_files to user repo

For the input datastructure I could think of the following attributes:

```yaml
- name: name_of_the_flag -> will result in --name_of_the_flag
   type: "type of the flag such as common, build, test, ... -> defaults to common if not specified (we could also name it type_override since this is more precise what it should do)
   value: If a value is specified, we will generate something like --name_of_the_flag=value
   use_default_value_from: alternative to "value" (specify a bazel version from which the default value should be used. Not too sure about this though, we could simply specify the value since we don't expect the default value changing too often)
   description: Here we put all the information we want to be placed as comment over the generated flag
```

as a resulting rc file, I could imagine

```
# <description>
# link to the bazel docs/<user_bazel_version>/<name>
<type_override> --<name>=<value>
```

Happy to hear what you think about this.
